implement 'get count for next rank use case'
Stair-Crusher-Club/scc-server pull request #143
Opened 2023-04-23 13:32 UTC by bellatoris

2023-04-23 13:32 UTC, bellatoris commented
Current dependencies on/for this PR:
* main
  * **PR #140** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/140" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #141** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/141" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #142** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/142" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #143** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143?utm_source=stack-comment).

2023-04-24 15:22 UTC, Zeniuus commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +        val rank = currentRank.rank ?: accessibilityRankRepository.findByConquestCount(currentRank.conquestCount)?.rank!!
#142 에서 구현 보니까 로직 상으로는 rank가 non-null인 케이스는 없을 것 같은데, 걍 rank를 non-null로 바꾸면 어떨까유

2023-04-30 07:59 UTC, bellatoris commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +        val rank = currentRank.rank ?: accessibilityRankRepository.findByConquestCount(currentRank.conquestCount)?.rank!!
근데 처음에 save 할 때 rank null 되어야 하지 않아요?

2023-04-30 12:15 UTC, Zeniuus commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +        val rank = currentRank.rank ?: accessibilityRankRepository.findByConquestCount(currentRank.conquestCount)?.rank!!
save를 entity로 하지 말고, 뭔가 메모리에서만 쓰는 중간 builder 객체같은 걸 만들면 어떨까 싶었습니다. 좀 귀찮긴 하지만... rank는 non-null이다가 굉장히 유용한 도메인 규칙인 것 같아서요.

2023-04-30 12:34 UTC, bellatoris commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +        val rank = currentRank.rank ?: accessibilityRankRepository.findByConquestCount(currentRank.conquestCount)?.rank!!
흠 좀 고민해볼게요

2023-04-30 14:48 UTC, bellatoris commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +        val rank = currentRank.rank ?: accessibilityRankRepository.findByConquestCount(currentRank.conquestCount)?.rank!!
걍 non-null을 생각해냄

2023-04-30 15:02 UTC, Zeniuus requested changes

2023-04-30 15:02 UTC, Zeniuus commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +            val nextRank = accessibilityRankRepository.findByRank(rank - 1)!!
근데 이거 내 위가 공동 n등이면 -1로는 안 되지 않나요? less than & order by rank desc limit 1을 해야 할 것 같기도...

2023-05-01 08:03 UTC, bellatoris commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +            val nextRank = accessibilityRankRepository.findByRank(rank - 1)!!
rank로 검색하는거라 괜찮지 않나요? 어떤 경우에 문제가 되는지 좀 더 자세히 설명해주실 수 있나요?

2023-05-01 14:19 UTC, Zeniuus commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +            val nextRank = accessibilityRankRepository.findByRank(rank - 1)!!
내 위가 공동 3등 3명이고 내가 6등이면, rank = 6이고 rank - 1 = 5일 테니까 nextRank가 null일 것 같습니다.

2023-05-01 14:37 UTC, bellatoris commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +            val nextRank = accessibilityRankRepository.findByRank(rank - 1)!!
아 그렇네 바보였습ㄴㅣ다 ㅋㅋ

2023-05-05 09:03 UTC, Zeniuus approved these changes

2023-05-05 09:03 UTC, Zeniuus commented on subprojects/bounded_context/accessibility/application/src/main/kotlin/club/staircrusher/accessibility/application/port/in/GetCountForNextRankUseCase.kt
> +            val nextRank = accessibilityRankRepository.findByRank(rank - 1)!!
#150 에서 해결된 것 확인

2023-05-07 09:14 UTC, bellatoris commented
@bellatoris queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143).

2023-05-07 09:17 UTC, bellatoris commented
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143) rebased this pull request as part of a merge.

2023-05-07 09:18 UTC, merged

2023-05-07 09:18 UTC, bellatoris commented
@bellatoris merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/143).