change application configuration
Stair-Crusher-Club/scc-server pull request #177
Opened 2023-07-31 16:29 UTC by bellatoris

## Checklist
- [ ] 충분한 양의 자동화 테스트를 작성했는가?
  - 계단정복지도 서비스는 사이드 프로젝트로 진행되는 만큼 충분한 QA 없이 배포되는 경우가 많습니다. 따라서 자동화 테스트를 꼼꼼하게 작성하는 것이 서비스 품질을 유지하는 데 매우 중요합니다.

2023-07-31 16:29 UTC, bellatoris commented
Current dependencies on/for this PR:
* main
  * **PR #172** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/172" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #173** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/173" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #174** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/174" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #175** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/175" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #176** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/176" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #177** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177?utm_source=stack-comment).

2023-08-06 05:35 UTC, Zeniuus requested changes
까먹방) github action secret에 있는 k3s kubeconfig 파일도 바꿔줘야 할 듯

2023-08-06 05:35 UTC, Zeniuus commented on infra/helm/scc-server/files/dev/application.yaml
> +      bucketname: scc-dev-accessibility-images-2
😭

2023-08-06 05:35 UTC, Zeniuus commented on infra/helm/scc-server/files/dev/application.yaml
> +      bucketname: scc-dev-accessibility-images-2
근데 생각해보니 애플리케이션을 일단 이렇게 배포하더라도, 동작에는 문제가 없는 게 맞죠? 걍 이미지가 s3 버킷 두 개 / aws 계정 두 개에 분산되는 게 문제인 거고.

2023-08-06 05:35 UTC, Zeniuus commented on infra/helm/scc-admin-frontend/values-dev.yaml
> -  repository: public.ecr.aws/q0g6g7m8/scc-admin-frontend
q0g6g7m8 라는 문자열로 검색하면 이미지를 푸시하는 쪽에 남아 있는 듯 합니다.

2023-08-06 05:35 UTC, Zeniuus commented on infra/helm/scc-server/values-dev.yaml
> -  awsRoleArn: arn:aws:iam::833004893731:role/scc-deploy-secret-dev
833004893731도 github action 중 이미지 푸시하는 쪽에 아직 남아 있네욤

2023-08-06 12:10 UTC, bellatoris commented on infra/helm/scc-server/files/dev/application.yaml
> +      bucketname: scc-dev-accessibility-images-2
네 동작은 문제 없어요. 돈이 두군데서 나가는게 문제일 것 같아요

2023-08-06 12:10 UTC, bellatoris commented on infra/helm/scc-admin-frontend/values-dev.yaml
> -  repository: public.ecr.aws/q0g6g7m8/scc-admin-frontend
아하... 네네 거기도 수정할게요

2023-08-06 12:11 UTC, bellatoris commented on infra/helm/scc-server/values-dev.yaml
> -  awsRoleArn: arn:aws:iam::833004893731:role/scc-deploy-secret-dev
ㅇㅋㅇㅋ

2023-08-06 12:18 UTC, bellatoris commented
> 까먹방) github action secret에 있는 k3s kubeconfig 파일도 바꿔줘야 할 듯

아 이런

2023-08-06 12:19 UTC, bellatoris commented
> > 까먹방) github action secret에 있는 k3s kubeconfig 파일도 바꿔줘야 할 듯
> 
> 아 이런

github action은 terraform으로 되면 좋을 것 같네요

2023-08-06 12:20 UTC, bellatoris commented
https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_environment_secret

2023-08-08 06:49 UTC, Zeniuus approved these changes
수정한 거 뒤에서 확인함

2023-08-13 12:50 UTC, bellatoris commented
@bellatoris started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177).

2023-08-13 12:55 UTC, bellatoris commented
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177) rebased this pull request as part of a merge.

2023-08-13 12:56 UTC, merged

2023-08-13 12:56 UTC, bellatoris commented
@bellatoris merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177).

2023-08-13 12:56 UTC, bellatoris commented
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.