change repoistory and account
Stair-Crusher-Club/scc-server pull request #181
Opened 2023-08-07 13:51 UTC by bellatoris

## Checklist
- [ ] 충분한 양의 자동화 테스트를 작성했는가?
  - 계단정복지도 서비스는 사이드 프로젝트로 진행되는 만큼 충분한 QA 없이 배포되는 경우가 많습니다. 따라서 자동화 테스트를 꼼꼼하게 작성하는 것이 서비스 품질을 유지하는 데 매우 중요합니다.

2023-08-07 13:51 UTC, bellatoris commented
Current dependencies on/for this PR:
* main
  * **PR #172** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/172" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #173** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/173" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #174** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/174" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #175** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/175" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #176** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/176" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #177** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/177" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #181** <a href="https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181?utm_source=stack-comment).

2023-08-08 06:47 UTC, Zeniuus approved these changes

2023-08-08 08:09 UTC, Zeniuus requested changes

2023-08-08 08:09 UTC, Zeniuus commented on app-admin-frontend/docker-push.sh
> +docker buildx build --platform linux/amd64 -t public.ecr.aws/i6n1n6v2/scc-admin-frontend:$IMAGE_TAG .
이거 위에 ecr login 하는 곳이 안 바뀌어 있어유

텍스트로 전체검색 해야 할 듯?

2023-08-08 08:30 UTC, bellatoris commented on app-admin-frontend/docker-push.sh
> +docker buildx build --platform linux/amd64 -t public.ecr.aws/i6n1n6v2/scc-admin-frontend:$IMAGE_TAG .
no way

2023-08-09 05:30 UTC, Zeniuus commented on app-admin-frontend/docker-push.sh
> +docker buildx build --platform linux/amd64 -t public.ecr.aws/i6n1n6v2/scc-admin-frontend:$IMAGE_TAG .
[73725af](https://github.com/Stair-Crusher-Club/scc-server/pull/183/commits/73725afe531bef172267b83d9972871ab0cf9f51) 걍 #183 에서 처리함

2023-08-09 05:30 UTC, Zeniuus approved these changes

2023-08-13 12:50 UTC, bellatoris commented
@bellatoris started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181).

2023-08-13 12:52 UTC, bellatoris commented on app-admin-frontend/docker-push.sh
> +docker buildx build --platform linux/amd64 -t public.ecr.aws/i6n1n6v2/scc-admin-frontend:$IMAGE_TAG .
감사합니다

2023-08-13 12:56 UTC, bellatoris commented
[Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181) failed to merge this pull request for an unknown reason. Try your merge again, or report a bug if you see this consistently.

2023-08-13 23:04 UTC, bellatoris commented
@bellatoris started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181).

2023-08-13 23:05 UTC, merged

2023-08-13 23:05 UTC, bellatoris commented
@bellatoris merged this pull request with [Graphite](https://app.graphite.dev/github/pr/Stair-Crusher-Club/scc-server/181).