ListChallenges 구현하기
Stair-Crusher-Club/scc-server pull request #204
Opened 2023-09-18 14:44 UTC by yongseongkim

## Checklist
- [ ] 충분한 양의 자동화 테스트를 작성했는가?
  - 계단정복지도 서비스는 사이드 프로젝트로 진행되는 만큼 충분한 QA 없이 배포되는 경우가 많습니다. 따라서 자동화 테스트를 꼼꼼하게 작성하는 것이 서비스 품질을 유지하는 데 매우 중요합니다.

2023-09-18 14:46 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +    }
내가 참여한 챌린지 + 내가 참여하지 않은 챌린지
차례대로 보여주기 위해 추가한 옵션

2023-09-24 05:56 UTC, Zeniuus approved these changes
아 역시 그냥 status를 두는 게 낫나 싶기도 하고...

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/main/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ChallengeController.kt
> +            }
컨트롤러에는 로직을 없애고, 다른 곳처럼 XxxUseCase로 빼면 좋겠습니다.

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +    fun getInProgressChallenges(option: MyChallengeOption? = null): List<Challenge> {
얘도 XxxUseCase 클래스의 private method로 갈 수 있을 듯!

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +    AND challenge.ends_at < :endRangeOfEndsAt
ends_at이 null인 경우는 별도로 고려해주면 좋을 것 같습니다.

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +ORDER BY my_participations.created_at DESC;
데이터가 많을 경우, 정렬 기준이랑 WHERE 절의 조건이랑 다르면 index가 제대로 활용되지 못합니다. 따라서 start_at으로 정렬하면 좋을 것 같아요.

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +    ON challenge.id = my_participations.challenge_id
저도 확신이 좀 없는데, 쿼리가 요런 형태면 challenge 하나하나마다 subquery를 evaluate 할 수도 있습니다. 그래서 explain을 해서 query plan을 한 번 보면 좋을 것 같아요. (challenge_partition을 uid로 먼저 필터링하는 것을 driving table로 쓰는지?)

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +ORDER BY challenge.created_at DESC;
여기도 정렬 기준과 WHERE절 기준 맞추기 & ends_at null인 케이스 고려하기!

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/main/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ChallengeController.kt
> +                                .map { it.toListChallengeDto(hasJoined = false, clock.instant()) }
어차피 페이징을 할 때 로직을 갈아 엎어야 할 것 같으니, 걍 challenge를 전체 조회한 후에 내가 참여한 챌린지를 맨 위로 정렬해도 괜찮았을 것 같네요 ㅋㅋ

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +                        startsAtRange = MIN.rangeTo(clock.instant()),
startsAt은 min ~ max 까지여야 하지 않나요? 오픈 예정인 것도 보여주는 것 같아서...

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +                    )
종료 기한이 없을 때는 isCompleted가 false인 것만 보여줘야 하려나요?

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
>          challengeRepository.removeAll()
ChallengeParticipation도 삭제?

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
> +                priority.indexOf(c1.status) < priority.indexOf(c2.status) -> 1
둘 다 1이면 좀 이상한디요? ㅋㅋ

2023-09-24 05:56 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
> +        assert(
뭔가 JUnit5의 Assertions를 사용하는 게 아니라 다른 assert를 사용하신 듯한...?

2023-09-24 05:56 UTC, Zeniuus requested changes
아 어프루브는 넘 습관적으로 눌렀습니다 ㅋㅋ
테스트 나이스!

2023-09-28 02:21 UTC, yongseongkim commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +ORDER BY my_participations.created_at DESC;
요구사항 중 하나가 내가 참여하는 챌린지는 참여한 시간으로 정렬하는건데 요건 다른 방식을 찾아봐야겠네요

2023-09-28 02:30 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/infra/src/main/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ChallengeController.kt
> +                                .map { it.toListChallengeDto(hasJoined = false, clock.instant()) }
페이징까지 구현하려다가 생각보다 복잡해서 이렇게했는데 수환님 말대로 해서 빠르게 개발하는것도 좋았을듯 ㅠ

2023-09-29 03:21 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +                    )
고거까지는 확인하지 않았는데 확인해볼게요

2023-09-29 03:24 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +                        startsAtRange = MIN.rangeTo(clock.instant()),
> 오픈 예정인 것도 보여주는 것 같아서

요부분 이해하지 못했습니다 ㅠ 진행중인 챌린지에 한해서 참여중인 여부를 확인하는게 요구사항이라 현재 시각 이후 startsAt 은 가져오지 않는게 맞습니다?

2023-09-29 03:37 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
> +                priority.indexOf(c1.status) < priority.indexOf(c2.status) -> 1
https://github.com/Stair-Crusher-Club/scc-server/pull/204/commits/01e4f1a352ab3ebcc6c2cba7dcee388cf4257230

2023-09-29 03:38 UTC, yongseongkim commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +    AND challenge.ends_at < :endRangeOfEndsAt
https://github.com/Stair-Crusher-Club/scc-server/pull/204/commits/d2368e80df1ef445a6ae06750546484af454b004

2023-09-29 03:38 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
> +        assert(
https://github.com/Stair-Crusher-Club/scc-server/pull/204/commits/df67f3e8f024c1de5717840643d778f7e8d4ec66

2023-09-29 03:38 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/infra/src/integrationTest/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ListChallengesTest.kt
>          challengeRepository.removeAll()
https://github.com/Stair-Crusher-Club/scc-server/pull/204/commits/975ef76243714d33709497a26535fc83e1f1e1ea

2023-09-29 03:45 UTC, yongseongkim commented on app-server/subprojects/bounded_context/challenge/infra/src/main/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ChallengeController.kt
> +            }
흠 제가 이해를 잘한건지 모르겠는데,
UseCase 는 port.in 에 존재하는 로직을 묶어 놓은거라고 생각했어요.
ex) 여러 service 들(place, accessibility, challenge 등) 을 조합해서 반복되는 데이터 추출하기 등

현재 코드는 DTO 를 port.in 객체로 변환하는 과정이라고 생각해서 UseCase 가 적합하지 않다고 생각하는데 맞나요?

2023-09-29 05:07 UTC, yongseongkim commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +    ON challenge.id = my_participations.challenge_id
수환님이 말씀하신 subquery 를 challenge 마다 evaluate 할 수 있다는 말은
WHERE 절에 걸린 challenge 를 가져오고
```sql
JOIN (
    SELECT *
    FROM challenge_participation
    WHERE challenge_participation.user_id = :userId
) AS my_participations
```
챌린지 마다 위와 같은 과정을 반복할 수 있다 일까요?

```SQL
EXPLAIN (SELECT *
FROM challenge
    JOIN (
        SELECT *
        FROM challenge_participation
        WHERE user_id = '8e0d5fec-b97d-4d02-9d3c-87a78b6b4ade'
    ) AS my_participations
    ON challenge.id = my_participations.challenge_id
WHERE
    to_timestamp('2023-07-01 20:54:31', 'YYYY-MM-DD HH24:MI:SS') < starts_at
    AND starts_at < to_timestamp('2023-10-01 20:54:31', 'YYYY-MM-DD HH24:MI:SS')
    AND to_timestamp('2023-07-01 20:54:31', 'YYYY-MM-DD HH24:MI:SS') < ends_at
    AND (ends_at IS NULL OR ends_at < to_timestamp('2023-10-01 20:54:31+00', 'YYYY-MM-DD HH24:MI:SS')));
```
```
 Nested Loop  (cost=0.00..15.58 rows=1 width=548)
   Join Filter: ((challenge.id)::text = (challenge_participation.challenge_id)::text)
   ->  Seq Scan on challenge_participation  (cost=0.00..13.25 rows=1 width=278)
         Filter: ((user_id)::text = '8e0d5fec-b97d-4d02-9d3c-87a78b6b4ade'::text)
   ->  Seq Scan on challenge  (cost=0.00..2.30 rows=2 width=270)
         Filter: ((to_timestamp('2023-07-01 20:54:31'::text, 'YYYY-MM-DD HH24:MI:SS'::text) < starts_at) AND (starts_at < to_timestamp('2023-10-01 20:54:31'::text, 'YYYY-MM-DD HH24:MI:SS'::text)) AND (to_timestamp('2023-07-01 20:54:31'::text, 'YYYY-MM-DD HH24:MI:SS'::text) < ends_at) AND ((ends_at IS NULL) OR (ends_at < to_timestamp('2023-10-01 20:54:31+00'::text, 'YYYY-MM-DD HH24:MI:SS'::text))))
```
요렇게 나오는데
'8e0d5fec-b97d-4d02-9d3c-87a78b6b4ade' 일치하는 challenge_participation
& 위 조건에 맞는 challenge 를 join 해서 가져오는거라 괜찮다?

2023-09-29 06:04 UTC, yongseongkim commented
우선 일부 리뷰만 반영한채로 머지하고 나머지 리뷰 뒤에 수정하겠습니다.

2023-09-29 06:04 UTC, merged

2023-09-29 08:52 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/infra/src/main/kotlin/club/staircrusher/challenge/infra/adapter/in/controller/ChallengeController.kt
> +            }
음 status에 따라서 분기를 타는 건 use case의 범위 안에 있다고 생각했습니다!

2023-09-29 09:34 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +ORDER BY my_participations.created_at DESC;
정렬 개귀찮 ㅋㅋ
현재 정렬 규칙이 너무 복잡한 것 같은데, 이러면 페이지네이션 넣었을 때 지옥일 거라 기획을 좀 단순화하면 좋을 것 같군요

2023-09-29 09:35 UTC, Zeniuus commented on app-server/subprojects/persistence_model/src/main/sqldelight/club/staircrusher/infra/persistence/sqldelight/query/challenge/Challenge.sq
> +    ON challenge.id = my_participations.challenge_id
오 네네 저러면 괜찮을 것 같습니다!

2023-09-29 09:39 UTC, Zeniuus commented on app-server/subprojects/bounded_context/challenge/application/src/main/kotlin/club/staircrusher/challenge/application/port/in/ChallengeService.kt
> +                        startsAtRange = MIN.rangeTo(clock.instant()),
아 그렇다면 코멘트 위치를 잘못 달았는데, MyChallengeOption.Without일 때는 오픈 예정인 것도 보여줘야 하니까 startsAtRange가 MIN.rangeTo(MAX)여야 하지 않을까 싶습니다! @yongseongkim